name: Check for misspells
on: [pull_request]
jobs:
  misspell:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
